# Generated by Django 4.1.7 on 2023-04-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_favourite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quntity",
            new_name="quantity",
        ),
    ]
